version: "2"
services:
  mysql-client:
    image: mysql:5.6
    container_name: mysql-client
    networks:
    - default
    - mysql_default
    environment: 
      MYSQL_ROOT_PASSWORD: PASSWORD
networks:
  mysql_default:
    external: true